// Code generated by "stringer -type Type -trimprefix Type"; DO NOT EDIT.

package demo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeSignon-1]
	_ = x[TypePacket-2]
	_ = x[TypeSyncTick-3]
	_ = x[TypeConsoleCmd-4]
	_ = x[TypeUserCmd-5]
	_ = x[TypeDataTables-6]
	_ = x[TypeStop-7]
	_ = x[TypeCustomData-8]
	_ = x[TypeStringTables-9]
}

const _Type_name = "SignonPacketSyncTickConsoleCmdUserCmdDataTablesStopCustomDataStringTables"

var _Type_index = [...]uint8{0, 6, 12, 20, 30, 37, 47, 51, 61, 73}

func (i Type) String() string {
	i -= 1
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
