// Code generated by "stringer -type SendPropType -trimprefix SendProp"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SendPropInt-0]
	_ = x[SendPropFloat-1]
	_ = x[SendPropVector-2]
	_ = x[SendPropVectorXY-3]
	_ = x[SendPropString-4]
	_ = x[SendPropArray-5]
	_ = x[SendPropDataTable-6]
	_ = x[SendPropInt64-7]
	_ = x[NumSendPropTypes-8]
}

const _SendPropType_name = "IntFloatVectorVectorXYStringArrayDataTableInt64NumSendPropTypes"

var _SendPropType_index = [...]uint8{0, 3, 8, 14, 22, 28, 33, 42, 47, 63}

func (i SendPropType) String() string {
	if i >= SendPropType(len(_SendPropType_index)-1) {
		return "SendPropType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SendPropType_name[_SendPropType_index[i]:_SendPropType_index[i+1]]
}
