// Code generated by "stringer -type SignonState -trimprefix SignonState"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SignonStateNone-0]
	_ = x[SignonStateChallenge-1]
	_ = x[SignonStateConnected-2]
	_ = x[SignonStateNew-3]
	_ = x[SignonStatePreSpawn-4]
	_ = x[SignonStateSpawn-5]
	_ = x[SignonStateFull-6]
	_ = x[SignonStateChangeLevel-7]
}

const _SignonState_name = "NoneChallengeConnectedNewPreSpawnSpawnFullChangeLevel"

var _SignonState_index = [...]uint8{0, 4, 13, 22, 25, 33, 38, 42, 53}

func (i SignonState) String() string {
	if i >= SignonState(len(_SignonState_index)-1) {
		return "SignonState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SignonState_name[_SignonState_index[i]:_SignonState_index[i+1]]
}
