// Code generated by "stringer -type Type"; DO NOT EDIT.

package kvpacker

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[String-1]
	_ = x[Int-2]
	_ = x[Float-3]
	_ = x[Ptr-4]
	_ = x[WString-5]
	_ = x[Color-6]
	_ = x[Uint64-7]
	_ = x[CompiledIntByte-8]
	_ = x[CompiledInt0-9]
	_ = x[CompiledInt1-10]
	_ = x[numTypes-11]
}

const _Type_name = "NoneStringIntFloatPtrWStringColorUint64CompiledIntByteCompiledInt0CompiledInt1numTypes"

var _Type_index = [...]uint8{0, 4, 10, 13, 18, 21, 28, 33, 39, 54, 66, 78, 86}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
